title: SCS-Maven-Plugin - Generate code based on AsyncApi and OpenApi specification.
description: Built by Corunet, SCS-Maven-Plugin is an open-source, Maven plugin that allows generating code based on AsyncApi and OpenApi specifications.
twitter:
  username: corunet
  card: summary
image: /assets/corunet-logo.svg
logo: /assets/corunet-logo.svg
# show_downloads: true
# google_analytics:
theme: jekyll-theme-tactile
